# Site settings
title: rubycoloredglasses
description: > # this means to ignore newlines until "baseurl:"
  I am Jason Miller, a web applications developer in the San Francisco Bay area.
url: 'http://blog.redconfetti.com'
baseurl: '/'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Jason Miller'
  email: jason@redconfetti.com
  twitter_username: redconfetti
  facebook_username: redconfetti
  github_username:  redconfetti
  linkedin_username:  redconfetti

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
